// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
const {chromium}=require(process.env.CHESS_REVIEW_PLAYWRIGHT||require.resolve('playwright'));
const fs=require('fs'),path=require('path'),assert=require('assert');const input=process.argv[2],out=process.argv[3];if(!input||!out)throw new Error('Usage: node check_leaks.cjs page.html screenshot-directory');const {pathToFileURL}=require('url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHESS_REVIEW_BROWSER?{executablePath:process.env.CHESS_REVIEW_BROWSER}:{})});try{const p=await browser.newPage({viewport:{width:1440,height:1150}});let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve(input)).href);let d=await p.locator('#visual-data').textContent().then(JSON.parse);assert.equal(await p.locator('#groups button').count(),d.groups.length);fs.mkdirSync(out,{recursive:true});assert(await p.evaluate(()=>{let ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.length===new Set(ids).size}));assert.equal(await p.locator('.reading, a[download]').count(),0);assert(await p.locator('#leaks-panel').isVisible());assert(await p.locator('#positive-section').isHidden());assert.equal(await p.locator('#leaks-tab').getAttribute('aria-selected'),'true');await p.screenshot({path:path.join(out,'leaks-default-desktop.png')});let checked=0;
for(let ci=0;ci<d.cases.length;ci++){const c=d.cases[ci];await p.locator('#groups button').nth(c.group).click();let local=d.cases.filter(x=>x.group===c.group).findIndex(x=>x.title===c.title);await p.locator('#cases button').nth(local).click();assert((await p.locator('#game-meta').innerText()).includes(c.side==='white'?'White':'Black'));assert.equal(await p.locator('#actual-title').innerText(),'What you played');assert.equal(await p.locator('#better-title').innerText(),'Recommended line');for(const key of ['actual','better']){assert.equal(await p.locator('#'+key+'-board').getAttribute('data-fen'),c.branches[key].frames[1].fen);assert((await p.locator('#'+key+'-move').innerText()).includes(c.branches[key].frames[1].san));}
await p.locator('#same').click();assert.equal(await p.locator('#actual-board').getAttribute('data-fen'),await p.locator('#better-board').getAttribute('data-fen'));assert.equal(c.branches.actual.frames[0].fen,c.branches.better.frames[0].fen);await p.locator('#results').click();for(const key of ['actual','better'])assert.equal(await p.locator('#'+key+'-board').getAttribute('data-fen'),c.branches[key].frames.at(-1).fen);await p.locator('#first-moves').click();
for(const [key,branch]of Object.entries(c.branches)){if(key==='threat'){assert(!(await p.locator('#extra-threat').getAttribute('open')));await p.locator('#extra-threat > summary').click();assert((await p.locator('#threat-card .route-tag').innerText()).includes('Not played in the game'));}const otherKey=key==='actual'?'better':'actual';const otherFen=await p.locator('#'+otherKey+'-board').getAttribute('data-fen');await p.locator('#'+key+'-moves button').first().click();for(let i=0;i<branch.frames.length;i++){let f=branch.frames[i];assert.equal(await p.locator('#'+key+'-board').getAttribute('data-fen'),f.fen);assert((await p.locator('#'+key+'-caption').innerText()).includes(f.caption));let count=f.fen.split(' ')[0].replace(/[0-9/]/g,'').length;assert.equal(await p.locator('#'+key+'-pieces img').count(),count);assert(await p.locator('#'+key+'-pieces img').evaluateAll(imgs=>imgs.every(x=>x.complete&&x.naturalWidth>0)));assert.equal(await p.locator('#'+otherKey+'-board').getAttribute('data-fen'),otherFen);if(i<branch.frames.length-1)await p.locator('#'+key+'-next').click();checked++;}assert(await p.locator('#'+key+'-next').isDisabled());}
}
await p.locator('#groups button').nth(0).click();await p.locator('#sequence').click();await p.waitForTimeout(3100);assert.equal(await p.locator('#actual-timeline').inputValue(),'1');assert.equal(await p.locator('#better-timeline').inputValue(),'0');await p.waitForTimeout(3000*(d.cases[0].branches.actual.frames.length-1));assert.equal(Number(await p.locator('#actual-timeline').inputValue()),d.cases[0].branches.actual.frames.length-1);assert.equal(await p.locator('#better-timeline').inputValue(),'1');if((await p.locator('#sequence').getAttribute('aria-pressed'))==='true')await p.locator('#sequence').click();await p.locator('#first-moves').click();await p.locator('#arrows').uncheck();assert.equal(await p.locator('#comparison .overlay path').count(),0);await p.locator('#arrows').check();const initialOrientation=await p.locator('#orientation').innerText();await p.locator('#flip').click();assert((await p.locator('#orientation').innerText()).includes(d.cases[0].side==='black'?'White':'Black'));await p.locator('#flip').click();assert.equal((await p.locator('#orientation').innerText()).split(' · ')[0],initialOrientation.split(' · ')[0]);
await p.locator('#player').evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+scrollY-15));await p.screenshot({path:path.join(out,'desktop.png')});
let progressFrames=0;if(d.progress?.length){await p.locator('#leaks-tab').focus();await p.keyboard.press('ArrowRight');assert(await p.locator('#positive-section').isVisible());assert(await p.locator('#leaks-panel').isHidden());assert.equal(await p.locator('#positive-nav').getAttribute('aria-selected'),'true');assert.equal(await p.evaluate(()=>document.activeElement.id),'positive-nav');await p.keyboard.press('ArrowLeft');assert(await p.locator('#leaks-panel').isVisible());await p.locator('#positive-nav').click();}
for(let i=0;i<(d.progress||[]).length;i++){await p.locator('#positive-tabs button').nth(i).click();const item=d.progress[i];assert.equal(await p.locator('#positive-title').innerText(),item.title);for(const role of ['prior','current']){const clip=item[role];if(!clip)continue;const pre='#positive-'+role;await p.locator(pre+'-reset').click();for(let n=0;n<clip.frames.length;n++){assert.equal(await p.locator(pre+'-board').getAttribute('data-fen'),clip.frames[n].fen);assert.equal(await p.locator(pre+'-caption').innerText(),clip.frames[n].caption);assert(await p.locator(pre+'-pieces img').evaluateAll(a=>a.every(x=>x.complete&&x.naturalWidth>0)));if(n<clip.frames.length-1)await p.locator(pre+'-next').click();progressFrames++;}assert(await p.locator(pre+'-next').isDisabled());}}
if(d.progress?.length){await p.locator('#positive-tabs button').first().click();await p.locator('#positive-current-reset').click();await p.locator('#positive-current-play').click();await p.waitForTimeout(3200);assert.equal(await p.locator('#positive-current-board').getAttribute('data-fen'),d.progress[0].current.frames[1].fen);await p.locator('#positive-tabs button').first().click();await p.locator('#positive-section').evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+scrollY-12));await p.screenshot({path:path.join(out,'progress-desktop.png')});}

for(const width of [390,320]){await p.locator('#leaks-tab').click();await p.setViewportSize({width,height:950});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:path.join(out,'leaks-default-mobile-'+width+'.png')});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const key of ['actual','better']){await p.locator('#'+key+'-card').evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+scrollY-12));await p.screenshot({path:path.join(out,'mobile-'+width+'-'+key+'.png')});assert(await p.locator('#'+key+'-card .jump-pair').isVisible());}let actual=await p.locator('#actual-card').boundingBox(),better=await p.locator('#better-card').boundingBox();assert(better.y>actual.y+actual.height-1);if(d.progress?.length){await p.locator('#positive-nav').click();await p.locator('#positive-cards').evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+scrollY-10));await p.screenshot({path:path.join(out,'progress-mobile-'+width+'.png')});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}}
if(d.progress?.length){
await p.locator('#positive-current-reset').click();await p.locator('#positive-current-play').click();await p.locator('#leaks-tab').click();const before=await p.locator('#positive-current-board').getAttribute('data-fen');await p.waitForTimeout(3200);assert.equal(await p.locator('#positive-current-board').getAttribute('data-fen'),before);
await p.locator('#positive-nav').click();await p.reload();assert(await p.locator('#positive-section').isVisible());assert(await p.locator('#leaks-panel').isHidden());
await p.goto(pathToFileURL(path.resolve(input)).href+'#player');assert(await p.locator('#leaks-panel').isVisible());assert(await p.locator('#positive-section').isHidden());
}
await p.locator('#leaks-tab').click();await p.context().setOffline(true);await p.reload();assert.equal(await p.locator('#actual-board').getAttribute('data-fen'),d.cases[0].branches.actual.frames[1].fen);if(!(await p.locator('#better-next').isDisabled()))await p.locator('#better-next').click();assert.equal(Number(await p.locator('#better-timeline').inputValue()),Math.min(2,d.cases[0].branches.better.frames.length-1));assert.equal(await p.locator('#actual-timeline').inputValue(),'1');assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'passed',clips:d.cases.length,frames:checked,progressRecords:(d.progress||[]).length,progressFrames,tabs:'leaks default; progress on demand; keyboard and deep links verified',independentBoards:true,sameStart:true,sequentialPlayback:true,offline:true,mobile:[390,320],errors}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
